UPDATE public.chapters
SET content = replace(
  replace(
    content,
    'She had apologised for the less-eating on the second morning — she was pregnant, and pregnant women ate less in the first weeks, not more, and her body was being efficient with the smaller quantities — and Sam had made her eat the rest of his portion at the second morning''s breakfast without argument. She had tried to argue. He had refused to let her. She had eaten. By the third day the pattern was set: Sam ate most of the rotbird, Ayel ate a small portion with the dried <em>agéli</em> to supplement the unfamiliar meat, and the unused pieces were buried carefully at each camp so as not to leave a trail.',
    'She had apologised for the less-eating on the second morning. Rotbird meat, she explained, did not agree with her. The taste was wrong, the texture was wrong, the fat layer had an aftertaste she could not identify, and her body was accepting the meat reluctantly in small portions rather than eagerly in large ones. The supplement of dried <em>agéli</em> from the Hjord encampment was what was keeping her upright. Sam had offered her the rest of his portion at the second morning''s breakfast, and she had refused it because her body had already registered that enough was enough, and Sam had accepted the refusal because Ayel was a druid and Ayel''s body told Ayel what Ayel''s body needed in a register Sam was not going to argue with. By the third day the pattern was set: Sam ate most of the rotbird, Ayel ate a small portion with the dried <em>agéli</em>, and the unused pieces were buried carefully at each camp so as not to leave a trail.'
  ),
  'Good. Ayel. I am Ayel. I am pregnant, two to three weeks along. The father is a Hjord named Theron. I am travelling with Sam because the two of us have been on the road together for three years and we make a good team. My eyes change colour. They are gold now because I am working. They will turn brown if I rest deeply tonight, which I am not going to do because the country is dangerous. I am Ayel.',
  'Good. Ayel. I am Ayel. I am a druid. I have been travelling with Sam for three years and we make a good team. My eyes change colour — they are gold now because I am working, and they will turn brown if I rest deeply, which I am not going to do tonight because the country is dangerous. My mother is Mira, who rules the mountain city Sam named. I am here because the road that is being built between our mountain and Arnis has to pass through this country and I am the one who was sent to ask permission. I am Ayel.'
),
updated_at = now()
WHERE chapter_number = 55;